language: python
python:
- '2.7'
install:
- pip install -e .
- pip install coveralls
- pip install sure
- pip install py-inspector
script:
- rm -rf .coverage
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: lojaintegrada
  on:
    tags: true
    repo: lojaintegrada/LI-Pagador-PagarMe
    all_branches: true
notifications:
  email:
    recipients:
    - contato@awsli.com.br
    - marcio.duarte@lojaintegrada.com.br
  hipchat:
    template:
      - '%{result} - %{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}) (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html